# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: NYU Communities of Practice
description: Bringing people together
tagline: Bringing people together
email: your-email@domain.com
url: //localhost:3000
thumb: roundicons-thumbnail.png

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: NYU CoP Committee
  email: jannae@nyu.edu
  bio:
  twitter:

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll Picture Tag Plugin Config
picture:
  source: _img-orig
  output: assets/img/resize
  markup: picture
  presets:
    main:
      attr:
        alt: 'main image'
      source_default:
        width: 600
    thumb:
      attr:
        alt: 'thumbnail'
      source_default:
        width: 400
        height: 289
    resource:
      source_default:
        width: 200
        height: 200
    profilepic:
      source_default:
        width: 225
        height: 225
