# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: NYU Torchtech Communities of Practice
description: NYU Torchtech Communities of Practice Website
tagline: Bringing people together
url: localhost:3000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

sass:
  sass_dir: _sass

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: CoP Committee
  email: cop-group@nyu.edu
  bio:
  twitter:

# general setting for Jekyll
googleAnalytics: UA-58340741-2

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10


# Build settings
markdown: kramdown
permalink: /:title

# Jekyll Picture Tag Plugin Config
picture:
  source: _img-originals
  output: assets/img
  markup: picture
  presets:
    main:
      attr:
        alt: 'main image'
      source_default:
        width: 600
    thumb:
      attr:
        alt: 'thumbnail'
      source_default:
        width: 400
        height: 289
    resource:
      source_default:
        width: 200
        height: 200
    profilepic:
      source_default:
        width: 225
        height: 225

#
# Plugin: jekyll-assets
#
assets:
  #
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  #
  dirname: assets
  #
  # Base URL of assets paths.
  #
  baseurl: /assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/js
    - _assets/css
    - _assets/img
  #
  # Sets JS compressor. No compression by default.
  # Possible variants: 'yui', 'uglifier', nil
  #
  js_compressor: uglifier
  #
  # Sets CSS compressor. No compression by default.
  # Possible variants: 'yui', 'sass', nil
  #
  css_compressor: sass
  #
  # Globally enables adding image width and height attributes to image tags.
  # Does nothing if either width or height attribute already set.
  # Disabled by default.
  #
  autosize: false
  #
  # Sets cachebusting policy for generated assets.
  #
  # Possible variants:
  #
  #   none - disables cachebusting
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css
  #
  #   soft - leave filenames as-is, but `?cb=<md5>` suffix for URLs generated
  #          with `asset_path`, `javascript` and `stylesheet`:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css?cb=4f41243847da693a4f356c0486114bc6
  #
  #   hard - (default) injects cachebusting checksum into processed filename:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app-4f41243847da693a4f356c0486114bc6.css
  #     output URL:   /assets/javascripts/app-4f41243847da693a4f356c0486114bc6.css
  #
  cachebust: hard
  #
  # Whenever or not cache compiled assets (disabled by default).
  # See `Compilation Cache` section of readme for details.
  #
  cache: false
  #
  # Specifies list of MIME types that needs to have gzipped versions.
  # You can set it to `false` to disable gzipping. Only javascripts and
  # stylesheets are gzipped by default.
  #
  gzip: [ text/css, application/javascript ]
  #
  # Does not concatenates files requested by `javascript` and `stylesheet`
  # helpers. Instead outputs multiple files in order they are required.
  # Default: false
  #
  debug: false
  #
  # Configuration version. Used to force cache invalidation.
  # Default: 1
  #
  version: 1
