# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: NYU Communities of Practice
description: Bringing people together
tagline: Bringing people together
email: your-email@domain.com
url: //localhost:3000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: NYU CoP Committee
  email: jannae@nyu.edu
  bio:
  twitter:

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

sass:
  sass_dir: _sass
  # style: compressed

# Team names, titles and social links
team:
  heading: CoP Operating Committee
  subheading: We put this together!
  subtext: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
  people:
    - name: Neyla Zonis
      pic: 1
      position: Committee Chair
      social:
        - title: twitter
          url: #
        - title: facebook
          url: #
        - title: stack-overflow
          url: #

    - name: Larry Parker
      pic: 2
      position: Lead Marketer
      social:
        - title: twitter
          url: #
        - title: facebook
          url: #
        - title: linkedin
          url: #

    - name: Diana Petersen
      pic: 3
      position: Lead Developer
      social:
        - title: twitter
          url: #
        - title: facebook
          url: #
        - title: google-plus
          url: #

modals:
  heading: "Join a Community"
  subheading: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

actionitems:
  heading: "Get Involved"
  subheading: "Action Items Subheading"
  anchor: actionitems
  sections:
    - title: "Join a Community"
      icon: group
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      link: '#join'
    - title: "Start a Community"
      icon: thumbs-up
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      link: '#'
    - title: "Find a Resource"
      icon: question
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      link: '#'
    - title: "Connect with Others"
      icon: comment
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      link: '#'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: '#'
  - title: facebook
    url: '#'
  - title: stack-overflow
    url: '#'
  - title: bitbucket
    url: '#'
  - title: github
    url: '#'

# Postal address (add as many lines as necessary)
address:
  - line: New York University, ITS
  - line: 10 Astor Pl
  - line: New York, NY 10003

# Build settings
markdown: kramdown
permalink: pretty